local f = io.open('BMW.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 BMW.sh')
os.execute('killall -9 tg')
os.execute('rm -rf BMW.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('BMW.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 BMW.sh')
os.execute('screen ./BMW.sh')
